wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.5
    code_path: code/train_mpe_curriculum_pb.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.2
